name: pizza_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  local_auth: ^2.2.0
  cloud_firestore: ^5.0.0
  collection: ^1.18.0
  flutter_credit_card: ^4.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/desserts/
    - assets/images/salads/
    - assets/images/tacos/
    - assets/images/drinks/
    - assets/images/burgers/
